[theme]
primaryColor = "#004d2e"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#000000"
font = "sans-serif"

[server]
headless = true

[browser]
gatherUsageStats = false