import os
import json
import pandas as pd
from docx import Document
from pptx import Presentation

DEMO_DIR = "frontend/demo_data"
os.makedirs(DEMO_DIR, exist_ok=True)

# Phase 1: Synthetic Data
with open(f"{DEMO_DIR}/phase1_sample_response.json", "w") as f:
    json.dump({
        "job_id": "demo_job_123",
        "scenario": {"natural_language": "Demo Scenario", "use_llm_profiler": False},
        "privacy": {"enabled": True, "epsilon": 1.0},
        "output_format": "csv",
        "profile_used": {
            "name": "Demo Profile",
            "variables": {
                "Revenue": {"type": "continuous"},
                "EBITDA": {"type": "continuous"}
            }
        },
        "validation_report": {
            "row_count": 1000,
            "correlation_rmse": 0.05,
            "dp_applied": True,
            "dp_epsilon": 1.0,
            "post_dp_ks_all_passed": True,
            "ks_tests": {
                "Revenue": {"statistic": 0.02, "p_value": 0.99, "passed": True},
                "EBITDA": {"statistic": 0.03, "p_value": 0.95, "passed": True}
            }
        }
    }, f, indent=2)

df = pd.DataFrame({
    "Revenue": [100, 110, 120, 130, 140],
    "EBITDA": [20, 22, 24, 26, 28]
})
df.to_csv(f"{DEMO_DIR}/phase1_sample_data.csv", index=False)

# Phase 2: Deliverable Engine
with open(f"{DEMO_DIR}/phase2_sample_response.json", "w") as f:
    json.dump({
        "job_id": "demo_memo_job_456",
        "status": "completed",
        "sections": [
            {"title": "Executive Summary", "content": "This is a demo executive summary.", "confidence": 0.95, "needs_review": False},
            {"title": "Investment Thesis", "content": "This is a demo investment thesis.", "confidence": 0.85, "needs_review": False},
            {"title": "Market Analysis", "content": "This is a demo market analysis.", "confidence": 0.45, "needs_review": True},
            {"title": "Financial Projections", "content": "This is a demo financial projection.", "confidence": 0.92, "needs_review": False},
            {"title": "Deal Structure", "content": "This is a demo deal structure.", "confidence": 0.88, "needs_review": False},
            {"title": "Risk Mitigation", "content": "This is a demo risk mitigation.", "confidence": 0.75, "needs_review": False}
        ],
        "download_urls": {
            "docx": "/demo_data/phase2_sample_memo.docx",
            "pptx": "/demo_data/phase2_sample_deck.pptx",
            "audit_trail": "/demo_data/audit_trail.json"
        }
    }, f, indent=2)

doc = Document()
doc.add_heading("Demo IC Memo", 0)
doc.add_paragraph("This is a generated IC Memo for the demo.")
doc.save(f"{DEMO_DIR}/phase2_sample_memo.docx")

prs = Presentation()
title_slide_layout = prs.slide_layouts[0]
slide = prs.slides.add_slide(title_slide_layout)
title = slide.shapes.title
subtitle = slide.placeholders[1]
title.text = "Demo Exec Deck"
subtitle.text = "Generated by Tracelight"
prs.save(f"{DEMO_DIR}/phase2_sample_deck.pptx")

# Phase 3: Compliance Engine
with open(f"{DEMO_DIR}/phase3_sample_response.json", "w") as f:
    json.dump({
        "job_id": "demo_comp_job_789",
        "status": "completed",
        "total_questions": 20,
        "auto_approved": 15,
        "needs_review": 5,
        "responses": [
            {
                "question_id": "Q1",
                "question_text": "Do you encrypt data at rest?",
                "domain": "Data Security",
                "response_type": "boolean",
                "status": "auto_approved",
                "confidence": 0.95,
                "boolean_value": True,
                "response_text": "Yes, we use AES-256 encryption."
            },
            {
                "question_id": "Q2",
                "question_text": "Describe your incident response plan.",
                "domain": "Incident Management",
                "response_type": "text",
                "status": "needs_review",
                "confidence": 0.65,
                "boolean_value": None,
                "response_text": "We have a 24/7 SOC."
            }
        ],
        "download_urls": {
            "csv": "/demo_data/phase3_sample_questionnaire.csv",
            "docx": "/demo_data/phase3_sample_completed.docx",
            "json": "/demo_data/phase3_sample_completed.json"
        }
    }, f, indent=2)

pd.DataFrame({
    "Question ID": ["Q1", "Q2"],
    "Question": ["Do you encrypt data at rest?", "Describe your incident response plan."],
    "Domain": ["Data Security", "Incident Management"]
}).to_csv(f"{DEMO_DIR}/phase3_sample_questionnaire.csv", index=False)

doc3 = Document()
doc3.add_heading("Completed Security Questionnaire", 0)
doc3.add_paragraph("Demo response to security questionnaire.")
doc3.save(f"{DEMO_DIR}/phase3_sample_completed.docx")

print("Demo fixtures created.")
